name: Document CLI Usage
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  document-cli-usage:
    name: document cli usage
    runs-on: ubuntu-latest
    env:
      DOCUMENT_CLI_USAGE_FILE: "CLI_USAGE.txt"
    permissions:
      contents: write
    steps:
      - name: Install dependencies
        run: |
          sudo apt install -y python3
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: build cli
        run: cargo build --release
      - name: run cli usage doc script
        run: python3 build-aux/document-cli-usage.py ${{ env.DOCUMENT_CLI_USAGE_FILE }}
      - name: git commit and push changed file
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --exit-code; then
            git add ${{ env.DOCUMENT_CLI_USAGE_FILE }}
            git commit -m "update ${{ env.DOCUMENT_CLI_USAGE_FILE }} from cli output"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
